-- CreateTable
CREATE TABLE `alunos` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(50) NOT NULL,
    `CPF` VARCHAR(14) NOT NULL,
    `TELEFONE` VARCHAR(30) NULL,
    `TELEFONE2` VARCHAR(30) NULL,
    `DATANASCIMENTO` DATE NULL,
    `ENDERECO` VARCHAR(200) NULL,
    `EMAIL` VARCHAR(35) NULL,
    `SITUACAO` VARCHAR(7) NULL,
    `PROFISSAO` VARCHAR(30) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
