-- CreateTable
CREATE TABLE "osteopatias" (
    "id" SERIAL NOT NULL,
    "idPaciente" INTEGER NOT NULL,
    "dataAvaliacao" DATE,
    "queixaPrincipal" VARCHAR(200),
    "historicoQueixa" VARCHAR(1000),
    "outrasQueixas" VARCHAR(500),
    "caracteristicaDor" VARCHAR(100),
    "horarioDor" VARCHAR(100),
    "oquePioraDor" VARCHAR(100),
    "oqueMelhoraDor" VARCHAR(100),
    "frequenciaDor" VARCHAR(7),
    "tratamentoDor" VARCHAR(100),
    "eva" INTEGER DEFAULT 0,
    "cirurgia" VARCHAR(1000),
    "halitose" VARCHAR(3) DEFAULT 'NÃO',
    "dorDeGarganta" VARCHAR(3) DEFAULT 'NÃO',
    "disfagia" VARCHAR(3) DEFAULT 'NÃO',
    "azia" VARCHAR(3) DEFAULT 'NÃO',
    "tosseSeca" VARCHAR(3) DEFAULT 'NÃO',
    "esofagite" VARCHAR(3) DEFAULT 'NÃO',
    "perdaPeso" VARCHAR(3) DEFAULT 'NÃO',
    "obsEsofago" VARCHAR(100),
    "diabete" VARCHAR(3) DEFAULT 'NÃO',
    "gordura" VARCHAR(3) DEFAULT 'NÃO',
    "infeccoes" VARCHAR(3) DEFAULT 'NÃO',
    "obsPancreas" VARCHAR(100),
    "HIPERTENSAO" VARCHAR(3) DEFAULT 'NÃO',
    "CALCULOS" VARCHAR(3) DEFAULT 'NÃO',
    "EDEMA" VARCHAR(3) DEFAULT 'NÃO',
    "URINASANGUE" VARCHAR(3) DEFAULT 'NÃO',
    "POUCAURINA" VARCHAR(3) DEFAULT 'NÃO',
    "MUITAURINA" VARCHAR(3) DEFAULT 'NÃO',
    "PERDAURINA" VARCHAR(3) DEFAULT 'NÃO',
    "DORURINAR" VARCHAR(3) DEFAULT 'NÃO',
    "QUEIMACAOURINAR" VARCHAR(3) DEFAULT 'NÃO',
    "ALTERACAOCLORACAO" VARCHAR(3) DEFAULT 'NÃO',
    "INFECCAORIM" VARCHAR(3) DEFAULT 'NÃO',
    "OBSRIM" VARCHAR(100),
    "dorEstomago" VARCHAR(3) DEFAULT 'NÃO',
    "eructacao" VARCHAR(3) DEFAULT 'NÃO',
    "refluxo" VARCHAR(3) DEFAULT 'NÃO',
    "hernia" VARCHAR(3) DEFAULT 'NÃO',
    "alimentosAcidos" VARCHAR(3) DEFAULT 'NÃO',
    "estufamento" VARCHAR(3) DEFAULT 'NÃO',
    "nauseas" VARCHAR(3) DEFAULT 'NÃO',
    "gastrite" VARCHAR(3) DEFAULT 'NÃO',
    "obsEstomago" VARCHAR(100),
    "perdaPesoFigado" VARCHAR(3) DEFAULT 'NÃO',
    "bocaAmarga" VARCHAR(3) DEFAULT 'NÃO',
    "desconfortoAbnominal" VARCHAR(3) DEFAULT 'NÃO',
    "congestaoIntestinal" VARCHAR(3) DEFAULT 'NÃO',
    "alimentosGordurosos" VARCHAR(3) DEFAULT 'NÃO',
    "ressaca" VARCHAR(3) DEFAULT 'NÃO',
    "hepatite" VARCHAR(3) DEFAULT 'NÃO',
    "obsFigado" VARCHAR(100),
    "medicacao" VARCHAR(500),
    "alimentacao" VARCHAR(500),
    "emocional" VARCHAR(500),
    "sono" VARCHAR(500),
    "atividadeFisica" VARCHAR(500),
    "trabalho" VARCHAR(500),
    "testesOrtopedicos" VARCHAR(1000),
    "testesOsteopaticos" VARCHAR(1000),
    "diagnosticoPorImagem" VARCHAR(1000),
    "diagnosticoTecidual" VARCHAR(1000),
    "diagnosticoOsteopatico" VARCHAR(1000),
    "constipacao" VARCHAR(3) DEFAULT 'NÃO',
    "hemorroidas" VARCHAR(3) DEFAULT 'NÃO',
    "diarreia" VARCHAR(3) DEFAULT 'NÃO',
    "sensacaoEvacuacao" VARCHAR(3) DEFAULT 'NÃO',
    "flatulencia" VARCHAR(3) DEFAULT 'NÃO',
    "qualidadeFezes" VARCHAR(3) DEFAULT 'NÃO',
    "obsIntestino" VARCHAR(100),
    "estufamentoAbdominal" VARCHAR(3) DEFAULT 'NÃO',
    "intolerancia" VARCHAR(3) DEFAULT 'NÃO',
    "colicas" VARCHAR(3) DEFAULT 'NÃO',
    "calculosBiliares" VARCHAR(3) DEFAULT 'NÃO',
    "obsVesiculaBiliar" VARCHAR(100),
    "dificuldadeMiccao" VARCHAR(3) DEFAULT 'NÃO',
    "diminuicaoMiccao" VARCHAR(3) DEFAULT 'NÃO',
    "obsProstata" VARCHAR(100),
    "dorPreMenstrual" VARCHAR(3) DEFAULT 'NÃO',
    "dorDuranteMenstruacao" VARCHAR(3) DEFAULT 'NÃO',
    "dorPosMenstrual" VARCHAR(3) DEFAULT 'NÃO',
    "menstruacaoIrregular" VARCHAR(3) DEFAULT 'NÃO',
    "dorRelacaoSexual" VARCHAR(3) DEFAULT 'NÃO',
    "dismenorreia" VARCHAR(3) DEFAULT 'NÃO',
    "amenorreia" VARCHAR(3) DEFAULT 'NÃO',
    "obsUtero" VARCHAR(100),
    "arritmia" VARCHAR(3) DEFAULT 'NÃO',
    "angina" VARCHAR(3) DEFAULT 'NÃO',
    "insuficienciaCardiaca" VARCHAR(3) DEFAULT 'NÃO',
    "hipertensaoSistemaCardiorespiratorio" VARCHAR(3) DEFAULT 'NÃO',
    "sindromeVasoVagal" VARCHAR(3) DEFAULT 'NÃO',
    "desmaios" VARCHAR(3) DEFAULT 'NÃO',
    "cansaco" VARCHAR(3) DEFAULT 'NÃO',
    "dispneia" VARCHAR(3) DEFAULT 'NÃO',
    "sinusite" VARCHAR(3) DEFAULT 'NÃO',
    "rinite" VARCHAR(3) DEFAULT 'NÃO',
    "bronquite" VARCHAR(3) DEFAULT 'NÃO',
    "asma" VARCHAR(3) DEFAULT 'NÃO',
    "pneumonia" VARCHAR(3) DEFAULT 'NÃO',
    "fumante" VARCHAR(3) DEFAULT 'NÃO',
    "maCirculacao" VARCHAR(3) DEFAULT 'NÃO',
    "varizes" VARCHAR(3) DEFAULT 'NÃO',
    "edemaMMSS" VARCHAR(3) DEFAULT 'NÃO',
    "edemaMMII" VARCHAR(3) DEFAULT 'NÃO',
    "obsSistemaCardiorespiratorio" VARCHAR(100),
    "peDireito" VARCHAR(20),
    "peDireitoVaro" VARCHAR(3) DEFAULT 'NÃO',
    "peDireitoValgo" VARCHAR(3) DEFAULT 'NÃO',
    "peDireitoPlano" VARCHAR(3) DEFAULT 'NÃO',
    "peDireitoCavo" VARCHAR(3) DEFAULT 'NÃO',
    "peEsquerdo" VARCHAR(20),
    "peEsquerdoVaro" VARCHAR(3) DEFAULT 'NÃO',
    "peEsquerdoValgo" VARCHAR(3) DEFAULT 'NÃO',
    "peEsquerdoPlano" VARCHAR(3) DEFAULT 'NÃO',
    "peEsquerdoCavo" VARCHAR(3) DEFAULT 'NÃO',
    "TesteInibicaoPodal" VARCHAR(3) DEFAULT 'NÃO',
    "txtTesteInibicaoPodal" VARCHAR(50),
    "classe1" VARCHAR(3) DEFAULT 'NÃO',
    "classe2" VARCHAR(3) DEFAULT 'NÃO',
    "aberta" VARCHAR(3) DEFAULT 'NÃO',
    "profunda" VARCHAR(3) DEFAULT 'NÃO',
    "classe3" VARCHAR(3) DEFAULT 'NÃO',
    "mordidaCruzadaD" VARCHAR(3) DEFAULT 'NÃO',
    "mordidaCruzadaE" VARCHAR(3) DEFAULT 'NÃO',
    "mordidaCruzadaB" VARCHAR(3) DEFAULT 'NÃO',
    "ausenciaDeDentes" VARCHAR(50),
    "TesteInibicaoATM" VARCHAR(3) DEFAULT 'NÃO',
    "txtTesteInibicaoATM" VARCHAR(50),
    "estrabismoConvergenteD" VARCHAR(3) DEFAULT 'NÃO',
    "estrabismoConvergenteE" VARCHAR(3) DEFAULT 'NÃO',
    "estrabismoDivergenteD" VARCHAR(3) DEFAULT 'NÃO',
    "estrabismoDivergenteE" VARCHAR(3) DEFAULT 'NÃO',
    "hipoconvergenciaD" VARCHAR(3) DEFAULT 'NÃO',
    "hipoconvergenciaE" VARCHAR(3) DEFAULT 'NÃO',
    "hipoconvergenciaBilateral" VARCHAR(3) DEFAULT 'NÃO',
    "testeInibicaoOlhos" VARCHAR(3) DEFAULT 'NÃO',
    "txtTesteInibicaoOlhos" VARCHAR(50),
    "cicatriz" VARCHAR(3) DEFAULT 'NÃO',
    "localCicatriz" VARCHAR(500),
    "testeInibicaoCicatriz" VARCHAR(3) DEFAULT 'NÃO',
    "txtTesteInibicaoCicatriz" VARCHAR(50),
    "lift" VARCHAR(3) DEFAULT 'NÃO',
    "txtLift" VARCHAR(50),
    "localViscera" VARCHAR(500),
    "testeInibicaoLift" VARCHAR(3) DEFAULT 'NÃO',
    "txtTesteInibicaoLift" VARCHAR(50),

    CONSTRAINT "osteopatias_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "osteopatias" ADD CONSTRAINT "osteopatias_idPaciente_fkey" FOREIGN KEY ("idPaciente") REFERENCES "pacientes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
