-- AlterTable
ALTER TABLE "atendimentos" ALTER COLUMN "observacao" SET DEFAULT 'COMPARECEU';

-- CreateTable
CREATE TABLE "avaliacoes" (
    "id" SERIAL NOT NULL,
    "idPaciente" INTEGER NOT NULL,
    "INDICACAO" VARCHAR(30),
    "ATIVIDADEFISICA" VARCHAR(3),
    "QUALATIVIDADEFISICA" VARCHAR(200),
    "MEDICACAO" VARCHAR(200),
    "TABAGISMO" VARCHAR(3),
    "ETILISMO" VARCHAR(3),
    "HIPERTENSAO" VARCHAR(3),
    "DOENCAS" VARCHAR(200),
    "DORES" VARCHAR(10000),
    "POSICAODOR" VARCHAR(10000),
    "OBJETIVOPRINCIPAL" VARCHAR(200),
    "QUEIXAPRINCIPAL" VARCHAR(200),
    "HDA" VARCHAR(10000),
    "HPP" VARCHAR(10000),
    "PESO" DECIMAL(5,2),
    "ALTURA" DECIMAL(5,2),
    "PA" VARCHAR(8),
    "PES" VARCHAR(200),
    "JOELHOS" VARCHAR(200),
    "PELVE" VARCHAR(200),
    "COLUNA" VARCHAR(200),
    "OMBROS" VARCHAR(200),
    "ESCAPULAS" VARCHAR(200),
    "CABECA" VARCHAR(200),

    CONSTRAINT "avaliacoes_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "avaliacoes" ADD CONSTRAINT "avaliacoes_idPaciente_fkey" FOREIGN KEY ("idPaciente") REFERENCES "pacientes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
